name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - uses: actions/checkout@v4

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 이미지 빌드 및 태그
      - name: Build and tag the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/elementart:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/elementart:latest ${{ secrets.DOCKER_USERNAME }}/elementart:master

      # 4. Docker 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/elementart:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/elementart:master
